---
driver:
  name: docker
  use_sudo: false
  socket: <%= ENV['DOCKER_HOST'] %>
  privileged: true
  provision_command:
    - yum install -y tar cronie crontabs sendmail

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4
  environments_path: 'test/environments' 

platforms:
- name: centos-7.0
  driver:
    dockerfile: test/cent7-dockerfile
    platform: centos
    run_command: /usr/sbin/init
  run_list:
  - recipe[yum]

suites:
- name: default
  attributes:
    chef_client:
        config:
          file_atomic_update: false
  run_list:
  - recipe[apache2_test::setup]
  - recipe[apache2_test::default]
  - recipe[apache2_test::basic_web_app]
  - recipe[apache2_test::broken_conf]
  - recipe[apache2_test::modules]
  - recipe[apache2_test::mod_ssl]
  - recipe[apache2_test::mod_auth_basic]
  - recipe[apache2_test::mod_auth_digest]
  - recipe[apache2_test::mod_authz_groupfile]
  - recipe[apache2_test::mod_authz_listed_host]
  - recipe[apache2_test::mod_authz_unlisted_host]
  - recipe[apache2_test::mod_authz_user]
  - recipe[apache2_test::mod_cgi]
  - recipe[apache2_test::mod_expires]
  - recipe[apache2_test::mod_status_remote]
  - recipe[apache2_test::mod_proxy_balancer]
- name: prefork
  includes: [
    'centos-6.5'
  ]
  attributes:
    apache:
      mpm: prefork
    chef_client:
        config:
          file_atomic_update: false
  run_list:
  - recipe[apache2_test::setup]
  - recipe[apache2_test::default]
  - recipe[apache2_test::broken_conf]
  - recipe[apache2_test::modules]
  - recipe[apache2_test::mod_cgi]
  - recipe[apache2_test::mod_fastcgi]
  - recipe[apache2_test::mod_perl]
  - recipe[apache2_test::mod_php5]
  - recipe[apache2_test::mod_python]
  - recipe[apache2_test::mod_ssl]
  - recipe[apache2_test::mod_proxy_balancer]
- name: worker
  includes: [
    'centos-7.0'
  ]
  attributes:
    apache:
      mpm: worker
    chef_client:
        config:
          file_atomic_update: false
  run_list:
  - recipe[apache2_test::setup]
  - recipe[apache2_test::default]
  - recipe[apache2_test::basic_web_app]
  - recipe[apache2_test::broken_conf]
  - recipe[apache2_test::modules]
  - recipe[apache2_test::mod_proxy_balancer]
