AllCops:
  Include:
    - metadata.rb
    - attributes/**/*
    - recipes/**/*
    - libraries/**/*
    - providers/**/*
    - resources/**/*
  Exclude:
    - test/**/*
    - vendor/**/*
    - libraries/artifactory*
    - Gemfile
  
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 14

Encoding:
  Exclude:
    - metadata.rb
    - Gemfile
    - knfife.circle.rb
